### ISSUE TITLE
Why is the fast-quorum for base epaxos N-1

### ISSUE THREAD

**Issue by pengsven** [efficient/epaxos#15]
hi,
I have a question for you, I am curious why the fast-quorm of base paxos is N-1 ?  but there is no detailed description in the paper

**Comment by imoraru** [comment]
N - 1 makes recovery very easy to reason about. N - 1 = 2F (because N = 2F + 1). Say 2F replicas have pre-accepted a proposal P. Then F replicas fail. Any recovering quorum will have at least F replicas that have pre-accepted P. If the leader of P is among them, it will be able to say whether it has committed P or not. If it is not, we can conclude that it must have also pre-accepted P, so now we know of at least N + 1 replicas that have pre-accepted P (N surviving + P's leader). They form a quorum, thus any conflicting P' must have a dependency on P (or vice-versa), therefore it's safe to re-propose and eventually commit P. 
In the paper, this is line 32 in Figure 3, and the proof sketch for Lemma 1 (execution consistency).

**Comment by pengsven** [comment]
thx.

**Comment by drmingdrmer** [comment]
Thanks for the clear explanation. BTW,

> If it is not, we can conclude that it must have also pre-accepted P, so now we know of at least N + 1 replicas that have pre-accepted P (N surviving + P's leader).

I think it should be `F` but not `N` up there, right?

**Comment by imoraru** [comment]
Oh, yes, thanks.
